// Generated by CoffeeScript 2.0.0-beta2
(function() {
  var BinaryLogicalOp, Parser;

  ({BinaryLogicalOp} = require("./node"));

  Parser = class Parser {
    constructor(token, ffi) {
      this.ffi = ffi;
      this.root = new BinaryLogicalOp("$and", token, null, null);
    }

    parse() {
      return this.root.parse();
    }

    gen_code(tree) {
      return tree != null ? tree.gen(this.ffi) : void 0;
    }

  };

  module.exports = Parser;

}).call(this);
