module.exports = 
  UNARY_LOGICAL_OPERATOR: "UNARY_LOGICAL_OPERATOR"
  BINARY_LOGICAL_OPERATOR: "BINARY_LOGICAL_OPERATOR"
  UNARY_RELATION_OPERATOR: "UNARY_RELATION_OPERATOR"
  BINARY_RELATION_OPERATOR: "BINARY_RELATION_OPERATOR"
  FIELD: "FIELD"
  # LEAFGRP: "LEAFGRP"
  LEAF: "LEAF"